### ISSUE TITLE
broken compact to full ctm

### ISSUE THREAD

**Issue by banhmikepxucxich** [ewanhowell5195/ewanhowell5195.github.io#1]
wierd
![oak](https://user-images.githubusercontent.com/62416957/127639772-321747c5-7bd0-4342-933f-c4e810439b12.png)
![oak_full_ctm](https://user-images.githubusercontent.com/62416957/127639779-cae0662b-f92a-48e7-b76a-f6d2e2b710e1.png)

**Comment by ewanhowell5195** [comment]
your input image is invalid.

![image](https://user-images.githubusercontent.com/48070995/127693696-5720c865-3b80-4c0a-8a79-29a7491acf57.png)
