### ISSUE TITLE
It didn't work.

### ISSUE THREAD

**Issue by tahiadz1962** [ewanhowell5195/ewanhowell5195.github.io#3]
I'm using the jsonOptimizer version on the default 1.19 textures, but they stayed the same after running the program. Can someone send me the completed resource pack or the solution to this problem?

**Comment by ewanhowell5195** [comment]
you used it on textures?

**Comment by tahiadz1962** [comment]
Yes.

**Comment by ewanhowell5195** [comment]
jsonOptimizer... is for json

textures... are not json
